name: Runner CI

on:
  workflow_dispatch:
  push:
    branches:
    - develop
    paths-ignore:
    - '**.md'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ~/
    steps:
    - name: Install Dependencies
      run: |
        ls
        npm install
    - name: Run Unit Tests
      run: |
        npm run test
    - name: Build Package
      run: |
        npm run build
    - name: Publish to Pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        publish_dir: ./_build/*
        github_token: ${{ secrets.PUB_PAGES }}
        silent: true
